package UIComponents.QuizzerWindow;

import UIComponents.QuizzerWindow.QuizzerPanel;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.swing.JCheckBox;

/**
 *
 * @author Armando
 */
public class CheckboxAnswerPanel extends AnswerPanel {
    private final List<JCheckBox> checkboxes;
//    private final QuizProblem quizProblem;
    
    public CheckboxAnswerPanel(Collection<String> choices, QuizzerPanel parentPanel) {
        JCheckBox cb;
        
        this.checkboxes = new ArrayList<>();
        
        for (String choice : choices) {
            cb = new JCheckBox(choice);
            cb.addItemListener((ItemEvent e) -> parentPanel.setSubmitEnabled(hasAnswer()));
//            if (quizProblem.hasUserAnswer() && quizProblem.getUserAnswers().indexOf(choice) != -1)
//                cb.setSelected(true);
            this.checkboxes.add(cb);
        }
        
//        this.quizProblem = quizProblem;
        initComponents();
    }
    
    @Override
    public final boolean hasAnswer() {
        for (JCheckBox button : checkboxes)
            if (button.isSelected())
                return true;
        
        return false;
    }
    
    @Override
    public List<String> getAnswers() {
        List<String> answers = new ArrayList<>();
        
        for (JCheckBox button : checkboxes)
            if (button.isSelected())
                answers.add(button.getText());
        
        return answers;
    }
    
    @Override
    public void clearAnswers() {
        for (JCheckBox checkbox : checkboxes)
            checkbox.setSelected(false);
    }
    
    /**
     * Creates new form RadiobuttonAnswerPanel
     */
//    public CheckboxAnswerPanel(List<JCheckBox> checkboxes) {
//        this.checkboxes = checkboxes;
//        
//        this.quizProblem = null;
//        if (problem.getAnswers().size() > 1) {
//            for (String choice : problem.getChoices()) {
//                JCheckBox cb = new JCheckBox(choice);
//                checkboxes.add(cb);
//                this.add(cb);
//            }
//        }
        
//        initComponents();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = (checkboxes.size() >= 1) ? checkboxes.get(0) : new JCheckBox();
        jCheckBox2 = (checkboxes.size() >= 2) ? checkboxes.get(1) : new JCheckBox();
        jCheckBox3 = (checkboxes.size() >= 3) ? checkboxes.get(2) : new JCheckBox();
        jCheckBox4 = (checkboxes.size() >= 4) ? checkboxes.get(3) : new JCheckBox();
        jCheckBox5 = (checkboxes.size() >= 5) ? checkboxes.get(4) : new JCheckBox();
        jCheckBox6 = (checkboxes.size() >= 6) ? checkboxes.get(5) : new JCheckBox();

        jCheckBox1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCheckBox1.setToolTipText("");

        jCheckBox2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCheckBox2.setToolTipText("");

        jCheckBox3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCheckBox3.setToolTipText("");

        jCheckBox4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jCheckBox5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jCheckBox6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox5, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox5))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox6))
                .addContainerGap())
        );

        jCheckBox2.setVisible(checkboxes.size() >= 2);
        jCheckBox3.setVisible(checkboxes.size() >= 3);
        jCheckBox4.setVisible(checkboxes.size() >= 4);
        jCheckBox5.setVisible(checkboxes.size() >= 5);
        jCheckBox6.setVisible(checkboxes.size() >= 6);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    // End of variables declaration//GEN-END:variables
}
