/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIComponents.QuizzerWindow;

import UIComponents.QuizzerWindow.QuizzerPanel;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author Armando
 */
public class RadiobuttonAnswerPanel extends AnswerPanel {
    private final List<JRadioButton> radiobuttons;
//    private final QuizProblem quizProblem;    
    private final ButtonGroup buttonGroup;
    
    public RadiobuttonAnswerPanel(Collection<String> choices, QuizzerPanel parentPanel) {
        JRadioButton rb;
        
        this.radiobuttons = new ArrayList<>();
        this.buttonGroup = new ButtonGroup();
        
        for (String choice : choices) {
            rb = new JRadioButton(choice);
            rb.addActionListener((ActionEvent e) -> parentPanel.setSubmitEnabled(true));
//            if (quizProblem.hasUserAnswer() && quizProblem.getUserAnswers().get(0).equals(choice))
//                rb.setSelected(true);
            this.buttonGroup.add(rb);
            this.radiobuttons.add(rb);
        }
        
//        this.quizProblem = quizProblem;
        initComponents();
    }
    
    @Override
    public boolean hasAnswer() {
        for (JRadioButton button : radiobuttons)
            if (button.isSelected())
                return true;
        
        return false;
    }
    
    @Override
    public List<String> getAnswers() {
        List<String> answers = new ArrayList<>();
        
        for (JRadioButton button : radiobuttons)
            if (button.isSelected())
                answers.add(button.getText());
        
        return answers;
    }

    @Override
    public void clearAnswers() {
        for (JRadioButton button : radiobuttons)
            button.setSelected(false);
    }
    
    
    
    /**
     * Creates new form CheckboxAnswerPanel
     */
//    public RadiobuttonAnswerPanel(List<JRadioButton> radiobuttons) {
//        this.radiobuttons = radiobuttons;
//        this.quizProblem = null;
//        this.buttonGroup = null;
//        initComponents();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        if (radiobuttons.size() >= 1) {
            jRadioButton1 = radiobuttons.get(0);
            jRadioButton2 = (radiobuttons.size() >= 2) ? radiobuttons.get(1) : new JRadioButton();
            jRadioButton3 = (radiobuttons.size() >= 3) ? radiobuttons.get(2) : new JRadioButton();
            jRadioButton4 = (radiobuttons.size() >= 4) ? radiobuttons.get(3) : new JRadioButton();
            jRadioButton5 = (radiobuttons.size() >= 5) ? radiobuttons.get(4) : new JRadioButton();
            jRadioButton6 = (radiobuttons.size() >= 6) ? radiobuttons.get(5) : new JRadioButton();

            jRadioButton1.setVisible(true);
            buttonGroup.add(jRadioButton1);
            jRadioButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        }
        else {
            jRadioButton1 = new JRadioButton();
            jRadioButton1.setVisible(false);
        }
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jRadioButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jRadioButton4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jRadioButton5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jRadioButton6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(jRadioButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton1))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jRadioButton3)
                        .addContainerGap())))
        );

        jRadioButton2.setVisible(radiobuttons.size() >= 2);
        jRadioButton3.setVisible(radiobuttons.size() >= 3);
        jRadioButton4.setVisible(radiobuttons.size() >= 4);
        jRadioButton5.setVisible(radiobuttons.size() >= 5);
        jRadioButton6.setVisible(radiobuttons.size() >= 6);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    // End of variables declaration//GEN-END:variables
}
