/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIComponents.QuizzerWindow;

import UIComponents.QuizzerWindow.QuizzerPanel;
import javax.swing.JTextField;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Armando
 */
public class SingleAnswerPanel extends AnswerPanel {
    private final JTextField textfield;
    
    /**
     * Creates new form TextAnswerPanel
     * @param parentPanel The parent panel of this SingleAnswerPanel
     */
    public SingleAnswerPanel(QuizzerPanel parentPanel) {
        super();
        textfield = new JTextField();
        textfield.setFont(new Font("Dialog", 0, 18));
        textfield.addActionListener((ActionEvent e) -> parentPanel.submit(e));
        textfield.getDocument().addDocumentListener(new QuizAnswerDocumentListener(textfield, parentPanel));
        
        initComponents();
    }
    
    @Override
    public boolean hasAnswer() {
        String answer = textfield.getText();
        return !(answer == null || answer.trim().length() <= 0);
    }
    
    public String getAnswer() {
        return textfield.getText().trim();
    }
    
    @Override
    public List<String> getAnswers() {
        List<String> result = new ArrayList<>();
        result.add(getAnswer());
        return result;
    }
    
    @Override
    public void clearAnswers() {
        textfield.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = textfield;

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
