/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIComponents.QuizzerWindow.GradePanel;

import java.util.List;
import java.util.Set;
import java.util.SortedSet;
import javax.swing.table.TableColumn;

/**
 * This is meant to show extra info about which answers were missed for a
 * graded multiple choice question. This is sized for the elaboration card panel.
 * @author Armando
 */
public class GradedQuizTableInfoPanel extends javax.swing.JPanel {
    private List<String> userAnswers;
    private Set<String> correctAnswers;
    private List<String> choices;
    
    /**
     * Creates new form GradedQuizListInfoPanel
     */
    public GradedQuizTableInfoPanel() {
        initComponents();
    }
    
    public GradedQuizTableInfoPanel(List<String> userAnswers
            , SortedSet<String> correctAnswers, List<String> choices) {
        this.userAnswers = userAnswers;
        this.correctAnswers = correctAnswers;
        this.choices = choices;
        initPanel();
        initComponents();
    }
    
    private void initPanel() {
        
    }
    
    public void setInfo(List<String> usrAns
            , Set<String> corrAns, List<String> choices) {
        this.userAnswers = usrAns;
        this.correctAnswers = corrAns;
        this.choices = choices;
        ChoicesMissedTableModel model;
        
        TableColumn column;
        ChoiceCellRenderer choiceRenderer;
        ChosenCellRenderer chosenRenderer;
        
        choiceRenderer = new ChoiceCellRenderer(usrAns, corrAns);
        chosenRenderer = new ChosenCellRenderer(corrAns, choices);
        
        column = table.getColumnModel().getColumn(1);
        column.setCellRenderer(choiceRenderer);
        column = table.getColumnModel().getColumn(3);
        column.setCellRenderer(choiceRenderer);
        
        column = table.getColumnModel().getColumn(0);
        column.setCellRenderer(chosenRenderer);
        column = table.getColumnModel().getColumn(2);
        column.setCellRenderer(chosenRenderer);
        
        model = (ChoicesMissedTableModel)table.getModel();
        model.setInfo(userAnswers, correctAnswers, choices);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpane = new javax.swing.JScrollPane();
        table = new ChoicesMissedTable(userAnswers, correctAnswers, choices);
        jLabel1 = new javax.swing.JLabel();

        scrollpane.setViewportView(table);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel1.setText("Incorrect answers are marked in red.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(0, 79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
