/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIComponents.QuizzerWindow.GradePanel;

/**
 * This is meant to show extra textual info, and is sized for the graded-quiz
 * report elaboration card panel.
 * @author Armando
 */
public class GradedQuizTextInfoPanel extends javax.swing.JPanel {
    private String text;
    
    /**
     * Creates new form QuizGradeElaborationPanel
     */
    public GradedQuizTextInfoPanel() {
        super();
        initPanel();
        initComponents();
    }
    
    public GradedQuizTextInfoPanel(String text) {
        super();
        this.text = text;
        initComponents();
        initPanel();
    }
    
    private void initPanel() {
        if (text != null)
            textarea.setText(text);
        else
            textarea.setText("Select a cell in the table for more info.");
    }
    
    public void setText(String newText) {
        if (newText != null) {
            textarea.setText(newText);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpane = new javax.swing.JScrollPane();
        textarea = new javax.swing.JTextArea();

        scrollpane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        textarea.setEditable(false);
        textarea.setColumns(20);
        textarea.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        textarea.setLineWrap(true);
        textarea.setRows(5);
        textarea.setWrapStyleWord(true);
        scrollpane.setViewportView(textarea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JTextArea textarea;
    // End of variables declaration//GEN-END:variables
}
